const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const LS={memories:'elsewhere_memories',prefs:'elsewhere_preferences',fancies:'elsewhere_fancies',places:'elsewhere_places',meals:'elsewhere_meals',sewing:'elsewhere_sewing',hugo:'elsewhere_hugo_confidence',active:'elsewhere_active'};
const safeJSON=(k,fallback)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(fallback))}catch{return fallback}};
const setJSON=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const uid=()=>`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const catIcon={make:'🎨',cook:'🍲',hugo:'🐕',explore:'🌿',sew:'🧵',rest:'🛋',new:'✨',brave:'🌱',other:'✦'};
const needOptions=[['head','🫧','Get out of my head'],['useful','✓','Feel useful'],['creative','🎨','Feel creative'],['move','🚶','Move my body'],['air','🌿','Fresh air'],['comfort','☕','Comfort'],['courage','🌱','A little courage'],['win','✦','A small win'],['off','🛋','Properly switch off'],['self','♡','Feel like myself'],['surprise','🎲','Surprise me']];
const logCats=[['cook','🍲 Cooked'],['make','🎨 Made'],['hugo','🐕 Hugo'],['explore','🌿 Explored'],['sew','🧵 Sewed'],['rest','🛋 Rested'],['new','✨ Tried something new'],['brave','🌱 Brave thing'],['other','✦ Something else']];

const activities=[
{id:'make-villa',cat:'make',e:['little','some','good'],n:['creative','self','head','surprise'],t:['30','60'],c:['work','off'],title:'Design an invitation for a wedding that does not exist',body:'Couple: Bea & Max. Venue: a faded Italian villa. Mood: late-summer, slightly glamorous, not too perfect.\n\nGive yourself permission to stop halfway through.',p:'It does not need to be useful to count.'},
{id:'make-palette',cat:'make',e:['empty','little','some'],n:['creative','head','self'],t:['10','30'],c:['work','off'],title:'Make a colour palette from today',body:'Choose one photo from today — sky, countryside, your kitchen, Hugo — and pull out five colours you like.',p:'You are allowed to choose colours simply because you like them.'},
{id:'make-dogmag',cat:'make',e:['little','some','good'],n:['creative','self','surprise'],t:['10','30'],c:['work','off'],title:'Photograph Hugo like a magazine cover',body:'Take ten photos. Try one low angle, one close-up and one completely ridiculous pose. Pick a favourite.',p:'A silly idea is still a creative idea.'},
{id:'make-hotel',cat:'make',e:['some','good'],n:['creative','self'],t:['30','60','evening'],c:['work','off'],title:'Brand an imaginary coastal hotel',body:'Give it a name, choose two fonts and three colours, then make a tiny logo or sign.',p:'Nobody is commissioning this. You cannot get it wrong.'},
{id:'make-photo5',cat:'make',e:['empty','little','some'],n:['head','creative','air'],t:['10','30'],c:['work','off'],title:'Take five photos of one thing',body:'Pick a theme: shadows, textures, green things, reflections, old doors, things shaped like circles. Take five and come home.',p:'You are noticing, not performing.'},
{id:'cook-tray',cat:'cook',e:['little','some','good'],n:['useful','win','self'],t:['30','60'],c:['work','off'],title:'Cook a lemon chicken traybake',body:'Chicken thighs, small potatoes, peppers, red onion and courgette. Toss with lemon, garlic, herbs and a little olive oil, then roast until golden.',p:'Dinner can be simple and still feel like something you made.'},
{id:'cook-pasta',cat:'cook',e:['little','some'],n:['useful','win','comfort'],t:['30'],c:['work','off'],title:'Make a proper tomato pasta',body:'Soften onion and garlic. Add tomatoes, spinach and chicken, beans or lentils. Toss through pasta and finish with herbs.',p:'You are allowed to learn dinner by dinner.'},
{id:'cook-eggs',cat:'cook',e:['empty','little'],n:['useful','win','comfort'],t:['10','30'],c:['work','off'],title:'Make eggs on toast, but make it nice',body:'Wholegrain toast, eggs however you like them, tomatoes or greens on the side. Add herbs or chilli if you fancy it.',p:'Healthy does not have to mean complicated.'},
{id:'cook-salmon',cat:'cook',e:['some','good'],n:['useful','self'],t:['30','60'],c:['work','off'],title:'Make salmon, greens and crushed potatoes',body:'Roast or pan-cook salmon. Crush cooked baby potatoes with lemon and herbs. Add a generous pile of greens.',p:'You do not have to cook like anyone else to make a good dinner.'},
{id:'cook-chilli',cat:'cook',e:['some','good'],n:['useful','win'],t:['60','evening'],c:['work','off'],title:'Make a big pot of chilli',body:'Use lean beef or turkey, beans, peppers, tomatoes, onion and spices. Make enough that tomorrow-you gets dinner too.',p:'Feeding yourself well is a practical kind of care.'},
{id:'hugo-tiny',cat:'hugo',e:['empty','little'],n:['air','courage','move','head','win'],t:['10','30'],c:['work','off'],title:'A tiny Hugo walk',body:'Take Hugo out on a route you already know. Let him sniff. Turn around whenever you want.',p:'Coming home early still counts as going out.'},
{id:'hugo-familiar',cat:'hugo',e:['little','some'],n:['courage','air','move','win'],t:['30','60'],c:['work','off'],title:'Take Hugo somewhere familiar — by yourself',body:'Choose somewhere you have been before and feel reasonably comfortable. No mileage target.',p:'The win is choosing to go, not how far you walk.'},
{id:'hugo-camera',cat:'hugo',e:['little','some','good'],n:['creative','air','head','self'],t:['30','60'],c:['work','off'],title:'Make the Hugo walk a photo mission',body:'Go somewhere familiar and look for three photographs worth taking. Let the camera give your brain something else to do.',p:'The walk does not have to be about being brave.'},
{id:'hugo-adventure',cat:'hugo',e:['some','good'],n:['courage','air','self'],t:['60','evening'],c:['off'],title:'Have a little adventure with Hugo',body:'Pick somewhere you would genuinely like to explore. Take your camera. You can turn around at any point.',p:'You do not have to prove anything to the walk.'},
{id:'explore-one',cat:'explore',e:['empty','little'],n:['head','air','creative','win'],t:['10','30'],c:['work','off'],title:'Go looking for one beautiful thing',body:'Step outside and find one thing worth photographing. It can be tiny.',p:'Curiosity is enough.'},
{id:'explore-road',cat:'explore',e:['little','some'],n:['air','move','head','courage'],t:['30'],c:['work','off'],title:'Walk somewhere you normally pass',body:'Choose a road, lane or footpath you usually ignore. Give it 15 minutes, then decide whether to continue.',p:'Exploring is allowed to be very small.'},
{id:'explore-village',cat:'explore',e:['some','good'],n:['air','creative','self'],t:['60','evening'],c:['off'],title:'Go somewhere you have never stopped before',body:'Choose a nearby village, viewpoint, garden or patch of countryside you have passed but never explored.',p:'There is no correct way to spend an afternoon.'},
{id:'explore-sunset',cat:'explore',e:['little','some','good'],n:['air','self','comfort','creative'],t:['30','60'],c:['work','off'],season:['summer'],title:'Go and watch the light change',body:'Pick somewhere with a view. Take a drink and your camera. Stay for as long as you want.',p:'You are allowed to go somewhere simply because it is beautiful.'},
{id:'sew-browse',cat:'sew',e:['empty','little'],n:['creative','self','win'],t:['10','30'],c:['work','off'],title:'Find one thing you would love to sew',body:'Browse beginner-friendly patterns and save one garment you would genuinely wear.',p:'Choosing what you like is part of making.'},
{id:'sew-kit',cat:'sew',e:['empty','little'],n:['useful','win'],t:['10','30'],c:['work','off'],title:'Build your sewing kit list',body:'Add three things you need before you start. Stop there. You do not need to buy anything tonight.',p:'Preparing counts as returning to a hobby.'},
{id:'sew-tiny',cat:'sew',e:['little','some'],n:['creative','win','self'],t:['10','30'],c:['work','off'],title:'Do one tiny sewing step',body:'If you have a project, do the next smallest thing: cut one piece, pin one seam, wind a bobbin or practise a stitch.',p:'You are not making the whole garment tonight.'},
{id:'rest-drink',cat:'rest',e:['empty','little'],n:['comfort','off','head'],t:['10','30','60','evening'],c:['work','off'],title:'Rest on purpose',body:'Make a drink. Put your phone across the room. Sit somewhere comfortable with Hugo, music, a book or just quiet.',p:'Rest chosen deliberately is not wasted time.'},
{id:'rest-shower',cat:'rest',e:['empty','little'],n:['comfort','off','self'],t:['30','60','evening'],c:['work','off'],title:'Make tonight comfortable',body:'Shower, clean pyjamas, something good to drink and something you actually want to watch. Leave the phone away from the sofa.',p:'Nothing needs fixing tonight.'},
{id:'rest-music',cat:'rest',e:['empty','little','some'],n:['head','comfort','self'],t:['10','30'],c:['work','off'],title:'Listen to three songs properly',body:'No scrolling. Choose three songs you love and just listen to them from start to finish.',p:'You do not have to make rest productive.'},
{id:'spring-blossom',cat:'explore',e:['little','some','good'],n:['air','creative','head'],t:['30','60'],c:['work','off'],season:['spring'],title:'Go looking for blossom',body:'Take a short walk and photograph three different kinds of blossom or new spring growth.',p:'Seasonal things are worth noticing because they do not last.'},
{id:'autumn-photo',cat:'explore',e:['little','some','good'],n:['air','creative','self'],t:['30','60'],c:['work','off'],season:['autumn'],title:'Photograph autumn colour',body:'Find the richest colour you can: leaves, berries, bracken, late flowers. Build a five-photo set.',p:'A season can be a reason to go outside.'},
{id:'winter-cosy',cat:'make',e:['little','some'],n:['creative','comfort','self'],t:['30','60'],c:['work','off'],season:['winter'],title:'Make something cosy and unnecessary',body:'Design a Christmas tag, sew a tiny decoration, make a paper star or create a winter photo card.',p:'Seasonal making is allowed to be delightfully pointless.'}
];
const tryIdeas=[['Creative','Spend 20 minutes trying simple hand embroidery.'],['Outside','Take a flask somewhere nearby and sit outside for ten minutes.'],['At home','Learn how to arrange flowers using whatever is already growing or inexpensive.'],['Food','Choose one vegetable you rarely cook and make it the best bit of dinner.'],['Learn','Watch one short beginner tutorial on something you have always wondered about, then stop.'],['Brave little things','Go into a café or shop on your own and choose something simply because you want it.'],['Creative','Try lino-style illustration digitally: one colour, bold shapes, no detail.'],['Outside','Take a photo walk with one rule: only photograph things below knee height.'],['Food','Make a dressing or sauce from scratch and build dinner around it.'],['At home','Rearrange one tiny corner of a room until you like looking at it.']];
const pointless=['Design a wedding invitation for an autumn elopement in Scotland.','Create a colour palette from the sky outside right now.','Photograph Hugo as if he is on the cover of a very serious magazine.','Design branding for an imaginary coastal hotel.','Create a poster for a fictional music festival in a field.','Photograph five objects in your house that are almost the same colour.','Design a menu for a dinner party that will never happen.','Create the packaging for an absurdly luxurious dog biscuit.','Design a save-the-date for a couple marrying in Copenhagen in winter.','Turn one of today’s photos into the cover of a novel.'];
const meals=[{id:'lemon-chicken',name:'Lemon chicken traybake',time:40,tags:['one tray','protein','lots of veg'],ingredients:'Chicken thighs, small potatoes, peppers, courgette, red onion, lemon, garlic, herbs.'},{id:'tomato-pasta',name:'Tomato, spinach & protein pasta',time:30,tags:['worknight','comforting'],ingredients:'Pasta, onion, garlic, tomatoes, spinach, chicken/beans/lentils, herbs.'},{id:'salmon-greens',name:'Salmon, greens & crushed potatoes',time:35,tags:['protein','simple'],ingredients:'Salmon, baby potatoes, greens, lemon, herbs.'},{id:'chilli',name:'Bean-packed chilli',time:55,tags:['batch cook','high fibre'],ingredients:'Lean beef/turkey or lentils, beans, peppers, onion, tomatoes, spices.'},{id:'shakshuka',name:'Shakshuka with wholegrain toast',time:30,tags:['vegetarian','one pan'],ingredients:'Eggs, peppers, tomatoes, onion, garlic, paprika, herbs, wholegrain bread.'},{id:'fish-tray',name:'Herby white fish with roast vegetables',time:35,tags:['light','protein'],ingredients:'White fish, tomatoes, courgette, peppers, baby potatoes, herbs, lemon.'}];
const hugoConfidenceItems=['Took Hugo out alone','Walked a familiar route alone','Drove somewhere with Hugo','Tried somewhere new','Stayed out longer than expected','Turned around when I wanted to','Felt nervous but went anyway'];
const defaultEquipment=['Sewing machine','Fabric scissors','Pins or clips','Tape measure','Seam ripper','Thread'];
const S={context:'work',energy:null,need:null,cat:null,time:null,current:null,feeling:null,again:null,freeCat:null,freeFeeling:null,freeAgain:null,eveningMode:0,hugoTab:'tiny'};
function prefs(){return safeJSON(LS.prefs,{loved:[],saved:[],blocked:[]})}function savePrefs(p){setJSON(LS.prefs,p)}
function memories(){return safeJSON(LS.memories,[])}function saveMemories(m){setJSON(LS.memories,m.slice(0,250))}
function season(){const m=new Date().getMonth()+1;return [12,1,2].includes(m)?'winter':[3,4,5].includes(m)?'spring':[6,7,8].includes(m)?'summer':'autumn'}
function partOfDay(){const h=new Date().getHours();return h<12?'morning':h<17?'afternoon':h<21?'evening':'late'}
function go(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.go===id));window.scrollTo(0,0);if(id==='things')renderThings();if(id==='cook')renderCook();if(id==='hugo')renderHugo();if(id==='sew')renderSew();if(id==='make')renderMake();if(id==='explore')renderExplore();if(id==='ideas')renderIdeas();if(id==='look')renderLook()}
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));$('#settingsBtn').onclick=()=>go('settings');
$('#needGrid').innerHTML=needOptions.map(([v,i,l])=>`<button class="need" data-v="${v}"><span>${i}</span>${l}</button>`).join('');
$('#logCats').innerHTML=logCats.map(([v,l])=>`<button class="logcat" data-v="${v}">${l}</button>`).join('');
function selectGroup(selector,key,after){$$(selector).forEach(b=>b.onclick=()=>{S[key]=b.dataset.v;$$(selector).forEach(x=>x.classList.toggle('selected',x===b));after?.();updateSuggest()})}
selectGroup('.context','context');selectGroup('.energy','energy');selectGroup('.need','need');selectGroup('.cat','cat');selectGroup('.time','time');
function updateSuggest(){$('#suggestBtn').disabled=!(S.energy&&S.need&&S.cat&&S.time)}
function activityScore(a){const p=prefs();if(p.blocked.includes(a.id))return -999;let score=0;if(S.cat==='surprise'||a.cat===S.cat)score+=5;else score-=5;if(a.e.includes(S.energy))score+=4;if(a.n.includes(S.need)||S.need==='surprise')score+=5;if(a.t.includes(S.time))score+=3;if(a.c.includes(S.context))score+=3;if(a.season?.includes(season()))score+=3;if(partOfDay()==='late'&&['60','evening'].includes(S.time)&&!['rest','make','sew'].includes(a.cat))score-=4;if(p.loved.includes(a.id))score+=2;return score+Math.random()*2}
function chooseActivity(forcePool){let pool=forcePool||activities;pool=[...pool].sort((a,b)=>activityScore(b)-activityScore(a));S.current=pool[0]||activities[0];renderActivity();go('activity')}
function renderActivity(){const a=S.current;$('#activityTag').textContent=`${catIcon[a.cat]||'✦'} ${a.cat.toUpperCase()}`;$('#activityDuration').textContent=S.time==='evening'?'The evening':`${S.time||10} min`;$('#activityTitle').textContent=a.title;$('#activityBody').textContent=a.body;$('#activityPermission').textContent=a.p;setJSON(LS.active,{a,time:S.time});const p=prefs();$('#loveActivity').classList.toggle('active',p.loved.includes(a.id));$('#saveActivity').classList.toggle('active',p.saved.includes(a.id));$('#lockBtn').textContent='▣ Put this on my lock screen';$('#lockNote').textContent='Close your phone and go do it. Elsewhere will wait.'}
$('#suggestBtn').onclick=()=>chooseActivity();$('#anotherBtn').onclick=()=>chooseActivity();
$('#escapeBtn').onclick=()=>{S.energy='empty';S.need='head';S.time='10';S.cat='surprise';chooseActivity(activities.filter(a=>a.e.includes('empty')&&a.t.includes('10')))};
$('#nothingBtn').onclick=()=>{S.energy='empty';S.need='comfort';S.time='30';S.cat='rest';chooseActivity(activities.filter(a=>a.cat==='rest'))};
function togglePref(kind){if(!S.current)return;const p=prefs();const arr=p[kind];const i=arr.indexOf(S.current.id);i>=0?arr.splice(i,1):arr.push(S.current.id);savePrefs(p);renderActivity()}
$('#loveActivity').onclick=()=>togglePref('loved');$('#saveActivity').onclick=()=>togglePref('saved');$('#blockActivity').onclick=()=>{const p=prefs();if(!p.blocked.includes(S.current.id))p.blocked.push(S.current.id);savePrefs(p);chooseActivity()};
async function lockNotification(title,body,tag='elsewhere-current'){if(!('Notification'in window)){alert('Lock-screen notifications are not supported by this browser.');return}let permission=Notification.permission;if(permission!=='granted')permission=await Notification.requestPermission();if(permission!=='granted'){alert('Allow notifications so Elsewhere can put this on your lock screen.');return}const reg=await navigator.serviceWorker.ready;await reg.showNotification(title,{body,icon:'./icon-elsewhere-v2.svg',badge:'./icon-elsewhere-v2.svg',tag,requireInteraction:true,actions:[{action:'done',title:'✓ I did it'},{action:'notdone',title:'Not today'}]})}
$('#lockBtn').onclick=async()=>{await lockNotification('Your Elsewhere thing',S.current.title);$('#lockBtn').textContent='✓ It is on your lock screen';$('#lockNote').textContent='Lock your phone. Elsewhere will wait.'};
$('#doneBtn').onclick=()=>{localStorage.removeItem(LS.active);go('complete')};$('#notDoneBtn').onclick=()=>{localStorage.removeItem(LS.active);go('notDone')};$('#smallerBtn').onclick=()=>{S.energy='empty';S.need='win';S.time='10';S.cat='surprise';chooseActivity(activities.filter(a=>a.t.includes('10')))};
function selectable(container,key){$$(container+' button').forEach(b=>b.onclick=()=>{S[key]=b.dataset.v;$$(container+' button').forEach(x=>x.classList.toggle('selected',x===b))})}selectable('#completionFeel','feeling');selectable('#completionAgain','again');selectable('#freeFeel','freeFeeling');selectable('#freeAgain','freeAgain');
async function fileToDataURL(file){if(!file)return null;return new Promise((resolve,reject)=>{const img=new Image(),r=new FileReader();r.onload=e=>{img.onload=()=>{const max=1000,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.72))};img.onerror=reject;img.src=e.target.result};r.onerror=reject;r.readAsDataURL(file)})}
async function saveCurrentCompletion(){if(!S.current)return;let photo=null;try{photo=await fileToDataURL($('#completionPhoto').files[0])}catch{}const m=memories();m.unshift({id:uid(),date:new Date().toISOString(),category:S.current.cat,title:S.current.title,note:$('#completionNote').value.trim(),feeling:S.feeling,again:S.again,safe:$('#completionSafe').checked,source:'prompt',activityId:S.current.id,photo});saveMemories(m);if(S.current.cat==='cook')upsertMealFromMemory(S.current.title,S.again);resetCompletion();go('today')}
function resetCompletion(){S.current=null;S.feeling=null;S.again=null;$('#completionNote').value='';$('#completionPhoto').value='';$('#completionSafe').checked=false;$$('#completionFeel button,#completionAgain button').forEach(b=>b.classList.remove('selected'))}
$('#saveCompletion').onclick=saveCurrentCompletion;
function generateEvening(mode=0){S.eveningMode=mode;const e=S.energy||'little',n=S.need||'self';let count=e==='empty'?2:e==='little'?3:4;if(mode<0)count=Math.max(2,count-1);if(mode>0)count=Math.min(4,count+1);let chosen=[];const add=cat=>{const pool=activities.filter(a=>a.cat===cat&&!chosen.includes(a));if(pool.length){const old=S.cat;S.cat=cat;pool.sort((a,b)=>activityScore(b)-activityScore(a));chosen.push(pool[0]);S.cat=old}};if(['air','move','courage','head'].includes(n))add('hugo');if(e!=='empty')add('cook');if(mode>0||['creative','self'].includes(n))add(Math.random()>.5?'make':'sew');add('rest');if(chosen.length<count)add('explore');chosen=chosen.slice(0,count);const plan=chosen.map(a=>({icon:catIcon[a.cat],title:a.title,detail:a.body.split('\n')[0],id:a.id}));setJSON('elsewhere_evening_plan',plan);renderEvening(plan);go('evening')}
function renderEvening(plan=safeJSON('elsewhere_evening_plan',[])){$('#eveningPlan').innerHTML=plan.map(x=>`<div class="planItem"><b>${x.icon}</b><div><strong>${esc(x.title)}</strong><small>${esc(x.detail)}</small></div></div>`).join('')||'<p class="muted">Choose your energy and what you need first.</p>'}
$('#shapeEvening').onclick=()=>generateEvening(0);$('#easierEvening').onclick=()=>generateEvening(-1);$('#interestingEvening').onclick=()=>generateEvening(1);$('#lockEvening').onclick=async()=>{const p=safeJSON('elsewhere_evening_plan',[]);await lockNotification('Your Elsewhere evening',p.map(x=>`${x.icon} ${x.title}`).join('\n'),'elsewhere-evening')};$('#eveningDone').onclick=()=>go('today');
function renderThings(){}
function mealState(){return safeJSON(LS.meals,{rated:{},ideas:[]})}function saveMealState(v){setJSON(LS.meals,v)}
function upsertMealFromMemory(name,again){const ms=mealState();ms.rated[name]=again||ms.rated[name]||'probably';saveMealState(ms)}
function renderCook(){const ms=mealState();const e=S.energy||'little';const dinner=[...meals].sort((a,b)=>{let sa=(e==='empty'?-(a.time):a.time<=40?3:1),sb=(e==='empty'?-(b.time):b.time<=40?3:1);return sb-sa})[Math.floor(Math.random()*Math.min(3,meals.length))];$('#dinnerCard').innerHTML=`<p class="eyebrow">TONIGHT'S DINNER</p><h2>${esc(dinner.name)}</h2><p class="muted">${esc(dinner.ingredients)}</p><p class="muted small">${dinner.time} min · ${dinner.tags.join(' · ')}</p><div class="rowActions"><button data-logmeal="${esc(dinner.name)}">I cooked this</button><button data-savefood="${esc(dinner.name)}">Save to try</button></div>`;const cooked=Object.entries(ms.rated);$('#canCookList').innerHTML=cooked.length?cooked.map(([n,r])=>`<div class="listItem"><strong>${esc(n)}</strong><small>${ratingLabel(r)}</small><div class="rowActions"><button data-rate="${esc(n)}|yes">❤️ Loved it</button><button data-rate="${esc(n)}|probably">👍 Make again</button><button data-rate="${esc(n)}|maybe">😐 Fine</button><button data-rate="${esc(n)}|no">🙅 Never again</button></div></div>`).join(''):'<p class="muted">Meals you actually cook will collect here.</p>';$('#foodIdeas').innerHTML=ms.ideas.length?ms.ideas.map(x=>`<div class="listItem"><strong>${esc(x.title)}</strong>${x.note?`<small>${esc(x.note)}</small>`:''}</div>`).join(''):'<p class="muted">Save recipes or meal ideas without committing to them tonight.</p>';bindCookActions()}
function ratingLabel(r){return {yes:'Loved it',probably:'Make again',maybe:'Fine',no:'Never again'}[r]||''}
function bindCookActions(){$$('[data-logmeal]').forEach(b=>b.onclick=()=>{const name=b.dataset.logmeal;const m=memories();m.unshift({id:uid(),date:new Date().toISOString(),category:'cook',title:`Cooked ${name}`,note:'',feeling:null,again:'probably',source:'free'});saveMemories(m);upsertMealFromMemory(name,'probably');renderCook()});$$('[data-savefood]').forEach(b=>b.onclick=()=>{const ms=mealState();if(!ms.ideas.some(x=>x.title===b.dataset.savefood))ms.ideas.unshift({id:uid(),title:b.dataset.savefood,note:''});saveMealState(ms);renderCook()});$$('[data-rate]').forEach(b=>b.onclick=()=>{const [n,r]=b.dataset.rate.split('|');const ms=mealState();ms.rated[n]=r;saveMealState(ms);renderCook()})}
$('#addFoodIdea').onclick=()=>openModal('SAVE A MEAL IDEA','What sounds good?',[{id:'title',label:'Meal or recipe',type:'text'},{id:'note',label:'Where did you see it / anything to remember?',type:'text'}],vals=>{const ms=mealState();ms.ideas.unshift({id:uid(),title:vals.title,note:vals.note});saveMealState(ms);renderCook()});
function hugoState(){return safeJSON(LS.hugo,{done:[],places:[]})}function saveHugo(v){setJSON(LS.hugo,v)}
function renderHugo(){const groups={tiny:activities.filter(a=>a.cat==='hugo'&&a.t.includes('10')),familiar:activities.filter(a=>a.cat==='hugo'&&['hugo-familiar','hugo-camera'].includes(a.id)),brave:activities.filter(a=>a.cat==='hugo'&&['hugo-adventure','hugo-familiar'].includes(a.id))};$('#hugoSuggestions').innerHTML=groups[S.hugoTab].map(a=>`<button class="listItem clickable" data-hugoact="${a.id}"><strong>${esc(a.title)}</strong><small>${esc(a.p)}</small></button>`).join('');const hs=hugoState();$('#hugoConfidence').innerHTML=hugoConfidenceItems.map(x=>`<label class="checkItem ${hs.done.includes(x)?'done':''}"><input type="checkbox" data-hugocheck="${esc(x)}" ${hs.done.includes(x)?'checked':''}><span>${esc(x)}</span></label>`).join('');$('#hugoPlaces').innerHTML=hs.places.length?hs.places.map(p=>`<div class="listItem"><strong>${esc(p.name)}</strong>${p.note?`<small>${esc(p.note)}</small>`:''}</div>`).join(''):"<p class=\"muted\">Save familiar places and places you’d like to try.</p>";$$('[data-hugoact]').forEach(b=>b.onclick=()=>{S.current=activities.find(a=>a.id===b.dataset.hugoact);S.time=S.current.t[0];renderActivity();go('activity')});$$('[data-hugocheck]').forEach(c=>c.onchange=()=>{const hs=hugoState();c.checked?(!hs.done.includes(c.dataset.hugocheck)&&hs.done.push(c.dataset.hugocheck)):hs.done=hs.done.filter(x=>x!==c.dataset.hugocheck);saveHugo(hs);renderHugo()})}
$$('#hugoTabs button').forEach(b=>b.onclick=()=>{S.hugoTab=b.dataset.tab;$$('#hugoTabs button').forEach(x=>x.classList.toggle('selected',x===b));renderHugo()});$('#addHugoPlace').onclick=()=>openModal('ADD A HUGO PLACE','Somewhere for the two of you',[{id:'name',label:'Place',type:'text'},{id:'note',label:'Why it feels useful / comfortable / interesting',type:'text'}],v=>{const hs=hugoState();hs.places.unshift({id:uid(),name:v.name,note:v.note});saveHugo(hs);renderHugo()});
function sewState(){return safeJSON(LS.sewing,{equipment:defaultEquipment.map(x=>({id:uid(),name:x,done:false})),wishlist:[],projects:[]})}function saveSew(v){setJSON(LS.sewing,v)}
function renderSew(){const s=sewState();$('#sewEquipment').innerHTML=s.equipment.map(x=>`<label class="checkItem ${x.done?'done':''}"><input type="checkbox" data-eqid="${x.id}" ${x.done?'checked':''}><span>${esc(x.name)}</span></label>`).join('');$('#sewWishlist').innerHTML=s.wishlist.length?s.wishlist.map(x=>`<div class="listItem"><strong>${esc(x.name)}</strong>${x.note?`<small>${esc(x.note)}</small>`:''}</div>`).join(''):'<p class="muted">Save garments you would genuinely love to wear.</p>';$('#sewProjects').innerHTML=s.projects.length?s.projects.map(x=>`<div class="listItem"><strong>${esc(x.name)}</strong><small>Next tiny step: ${esc(x.next||'Choose one tiny next step')}</small><div class="rowActions"><button data-nextproject="${x.id}">Change next step</button><button data-finishproject="${x.id}">I made it</button></div></div>`).join(''):'<p class="muted">No project needs to start until you are ready.</p>';$$('[data-eqid]').forEach(c=>c.onchange=()=>{const s=sewState(),x=s.equipment.find(y=>y.id===c.dataset.eqid);x.done=c.checked;saveSew(s);renderSew()});$$('[data-nextproject]').forEach(b=>b.onclick=()=>openModal('NEXT TINY STEP','What is the smallest useful next action?',[{id:'next',label:'Next step',type:'text'}],v=>{const s=sewState(),x=s.projects.find(y=>y.id===b.dataset.nextproject);x.next=v.next;saveSew(s);renderSew()}));$$('[data-finishproject]').forEach(b=>b.onclick=()=>{const s=sewState(),i=s.projects.findIndex(y=>y.id===b.dataset.finishproject);const [x]=s.projects.splice(i,1);saveSew(s);const m=memories();m.unshift({id:uid(),date:new Date().toISOString(),category:'sew',title:`Made ${x.name}`,note:'',feeling:'loved',again:'yes',source:'free'});saveMemories(m);renderSew()})}
$('#addEquipment').onclick=()=>openModal('ADD EQUIPMENT','One thing at a time',[{id:'name',label:'Item',type:'text'}],v=>{const s=sewState();s.equipment.push({id:uid(),name:v.name,done:false});saveSew(s);renderSew()});$('#addSewWish').onclick=()=>openModal('SAVE SOMETHING TO MAKE','No commitment required',[{id:'name',label:'What would you love to make?',type:'text'},{id:'note',label:'Pattern / fabric / idea',type:'text'}],v=>{const s=sewState();s.wishlist.unshift({id:uid(),name:v.name,note:v.note});saveSew(s);renderSew()});$('#addSewProject').onclick=()=>openModal('START A SEWING PROJECT','Make the first step tiny',[{id:'name',label:'Project',type:'text'},{id:'next',label:'First tiny step',type:'text'}],v=>{const s=sewState();s.projects.unshift({id:uid(),name:v.name,next:v.next});saveSew(s);renderSew()});
function renderMake(){newPointless();const p=prefs();const saved=activities.filter(a=>p.saved.includes(a.id)&&a.cat==='make');$('#creativeSaved').innerHTML=saved.length?saved.map(a=>`<div class="listItem"><strong>${esc(a.title)}</strong><small>${esc(a.p)}</small></div>`).join(''):'<p class="muted">Creative prompts you save will live here.</p>';const made=memories().filter(m=>m.category==='make').slice(0,12);$('#madeList').innerHTML=made.length?made.map(memoryHTML).join(''):'<p class="muted">Things you make will collect here — finished or not.</p>'}
function newPointless(){$('#pointlessPrompt').textContent=pointless[Math.floor(Math.random()*pointless.length)]}$('#pointlessBtn').onclick=newPointless;
function placeState(){return safeJSON(LS.places,{found:[],wish:[]})}function savePlaces(v){setJSON(LS.places,v)}
function renderExplore(){const ps=placeState();$('#foundPlaces').innerHTML=ps.found.length?ps.found.map(p=>`<div class="listItem"><strong>${esc(p.name)}</strong><small>${esc(p.note||'')}</small></div>`).join(''):'<p class="muted">Places you discover can live here.</p>';$('#wishPlaces').innerHTML=ps.wish.length?ps.wish.map(p=>`<div class="listItem"><strong>${esc(p.name)}</strong><small>${esc(p.note||'')}</small></div>`).join(''):'<p class="muted">Save somewhere that makes you think “one day”.</p>';$('#chosenPlace').textContent=ps.wish.length?ps.wish[Math.floor(Math.random()*ps.wish.length)].name:'Save a few places first.'}
$('#choosePlace').onclick=renderExplore;$('#addFoundPlace').onclick=()=>openModal('ADD A PLACE YOU FOUND','What do you want to remember?',[{id:'name',label:'Place',type:'text'},{id:'note',label:'What did you like?',type:'text'}],v=>{const ps=placeState();ps.found.unshift({id:uid(),name:v.name,note:v.note,date:new Date().toISOString()});savePlaces(ps);renderExplore()});$('#addWishPlace').onclick=()=>openModal('SOMEWHERE YOU FANCY','No plans required yet',[{id:'name',label:'Place',type:'text'},{id:'note',label:'Why did it catch your eye?',type:'text'}],v=>{const ps=placeState();ps.wish.unshift({id:uid(),name:v.name,note:v.note});savePlaces(ps);renderExplore()});
function fancyState(){return safeJSON(LS.fancies,[])}function saveFancies(v){setJSON(LS.fancies,v)}
function renderIdeas(){const fs=fancyState();$('#fancyList').innerHTML=fs.length?fs.map(x=>`<div class="listItem"><strong>${esc(x.title)}</strong><small>${esc(x.category)}${x.note?' · '+esc(x.note):''}</small></div>`).join(''):'<p class="muted">A place for recipes, patterns, places, books and “maybe one day”.</p>';newTry();const p=prefs(),saved=activities.filter(a=>p.saved.includes(a.id));$('#savedLaterList').innerHTML=saved.length?saved.map(a=>`<div class="listItem"><strong>${catIcon[a.cat]} ${esc(a.title)}</strong><small>${esc(a.p)}</small><div class="rowActions"><button data-openact="${a.id}">Do this</button></div></div>`).join(''):'<p class="muted">Activities you save for later will live here.</p>';$$('[data-openact]').forEach(b=>b.onclick=()=>{S.current=activities.find(a=>a.id===b.dataset.openact);S.time=S.current.t[0];renderActivity();go('activity')})}
function newTry(){const x=tryIdeas[Math.floor(Math.random()*tryIdeas.length)];$('#tryTitle').textContent=x[0];$('#tryBody').textContent=x[1]}$('#anotherTry').onclick=newTry;
$('#addFancy').onclick=()=>openModal('ADD SOMETHING I FANCY','Interesting things can wait here',[{id:'title',label:'What caught your eye?',type:'text'},{id:'category',label:'Category',type:'select',options:['Sewing','Recipe','Place','Craft','Photography','Book','Design','Exhibition','Something else']},{id:'note',label:'Anything to remember?',type:'text'}],v=>{const fs=fancyState();fs.unshift({id:uid(),date:new Date().toISOString(),...v});saveFancies(fs);renderIdeas()});
function monthMemories(){const now=new Date();return memories().filter(x=>{const d=new Date(x.date);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()})}
function memoryHTML(x){return `<div class="listItem"><small>${catIcon[x.category]||'✦'} ${(x.category||'other').toUpperCase()} · ${new Date(x.date).toLocaleDateString()}</small><strong>${esc(x.title)}</strong>${x.note?`<p>${esc(x.note)}</p>`:''}${x.photo?`<img class="memoryPhoto" src="${x.photo}" alt="Saved Elsewhere memory">`:''}</div>`}
function observation(ms){if(ms.length<4)return 'Nothing to analyse yet. Just keep noticing what feels good.';const counts={};ms.forEach(x=>counts[x.category]=(counts[x.category]||0)+1);const top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];const loved=ms.filter(x=>x.feeling==='loved');if(loved.length>=2){const lc={};loved.forEach(x=>lc[x.category]=(lc[x.category]||0)+1);const l=Object.entries(lc).sort((a,b)=>b[1]-a[1])[0];if(l)return `Looks like ${l[0]} things have given you some of your best moments this month.`}return top?`You seem to have been making room for more ${top[0]} lately.`:'Your month is starting to have a shape of its own.'}
function renderLook(){const all=memories(),ms=monthMemories(),cats=['cook','hugo','explore','make','sew','new'];$('#monthStats').innerHTML=cats.map(c=>`<div class="stat"><strong>${ms.filter(x=>x.category===c).length}</strong><span>${({cook:'dinners',hugo:'Hugo',explore:'places',make:'made',sew:'sewing',new:'new things'})[c]}</span></div>`).join('');$('#observation').textContent=observation(ms);const safe=all.filter(x=>x.safe).slice(0,8);$('#safeList').innerHTML=safe.length?safe.map(x=>`<div class="safeMemory">${esc(x.title)}${x.note?` — ${esc(x.note)}`:''}</div>`).join(''):'<p class="small" style="opacity:.8">You can collect moments here where something was imperfect, uncertain or vulnerable — and you were still okay.</p>';$('#memoryList').innerHTML=all.length?all.slice(0,30).map(memoryHTML).join(''):'<p class="muted">Nothing needs proving yet. When you do something, it can live here.</p>'}
$('#openAddMemory').onclick=()=>{resetFree();go('addMemory')};$('#quickSafe').onclick=()=>openModal('PROOF I WAS SAFE','What happened that could once have felt risky?',[{id:'title',label:'What did you try?',type:'text'},{id:'note',label:'What happened instead?',type:'text'}],v=>{const m=memories();m.unshift({id:uid(),date:new Date().toISOString(),category:'brave',title:v.title,note:v.note,feeling:null,again:null,safe:true,source:'free'});saveMemories(m);renderLook()});
selectable('#freeFeel','freeFeeling');selectable('#freeAgain','freeAgain');
$$('.logcat').forEach(b=>b.onclick=()=>{S.freeCat=b.dataset.v;$$('.logcat').forEach(x=>x.classList.toggle('selected',x===b));updateFree()});$('#freeTitle').addEventListener('input',updateFree);function updateFree(){$('#saveFree').disabled=!(S.freeCat&&$('#freeTitle').value.trim())}
function resetFree(){S.freeCat=null;S.freeFeeling=null;S.freeAgain=null;$('#freeTitle').value='';$('#freeNote').value='';$('#freePhoto').value='';$('#freeSafe').checked=false;$$('.logcat,#freeFeel button,#freeAgain button').forEach(x=>x.classList.remove('selected'));updateFree()}
$('#saveFree').onclick=async()=>{let photo=null;try{photo=await fileToDataURL($('#freePhoto').files[0])}catch{}const m=memories();m.unshift({id:uid(),date:new Date().toISOString(),category:S.freeCat,title:$('#freeTitle').value.trim(),note:$('#freeNote').value.trim(),feeling:S.freeFeeling,again:S.freeAgain,safe:$('#freeSafe').checked,source:'free',photo});saveMemories(m);if(S.freeCat==='cook')upsertMealFromMemory($('#freeTitle').value.trim(),S.freeAgain);resetFree();go('look')};
let modalCallback=null;function openModal(eyebrow,title,fields,cb){modalCallback=cb;$('#modalEyebrow').textContent=eyebrow;$('#modalTitle').textContent=title;$('#modalFields').innerHTML=fields.map(f=>f.type==='select'?`<label class="fieldLabel">${esc(f.label)}</label><select data-field="${f.id}">${f.options.map(o=>`<option>${esc(o)}</option>`).join('')}</select>`:`<label class="fieldLabel">${esc(f.label)}</label><input type="text" data-field="${f.id}">`).join('');$('#modal').classList.remove('hidden');$('#modal').dataset.fields=JSON.stringify(fields.map(f=>f.id))}
function closeModal(){$('#modal').classList.add('hidden');modalCallback=null}$('#modalClose').onclick=closeModal;$('#modalSave').onclick=()=>{const ids=JSON.parse($('#modal').dataset.fields||'[]'),vals={};ids.forEach(id=>vals[id]=$(`[data-field="${id}"]`).value.trim());if(!vals[ids[0]])return;const cb=modalCallback;closeModal();cb?.(vals)};
$('#clearPrefs').onclick=()=>{localStorage.removeItem(LS.prefs);alert('Suggestion preferences reset. Your memories are untouched.')};$('#clearAll').onclick=()=>{if(confirm('Clear all saved Elsewhere data from this device?')){Object.values(LS).forEach(k=>localStorage.removeItem(k));localStorage.removeItem('elsewhere_evening_plan');location.reload()}};
function restoreActive(){const x=safeJSON(LS.active,null);if(x?.a){S.current=x.a;S.time=x.time;return true}return false}
const d=new Date(),wd=d.getDay();S.context=(wd>=1&&wd<=5)?'work':'off';$$('.context').forEach(b=>b.classList.toggle('selected',b.dataset.v===S.context));$('#dayLabel').textContent=`${d.toLocaleDateString(undefined,{weekday:'long'}).toUpperCase()} · ${S.context==='work'?'WORKDAY':'DAY OFF'} · ${partOfDay().toUpperCase()}`;
if('serviceWorker' in navigator)window.addEventListener('load',async()=>{try{await navigator.serviceWorker.register('./sw.js')}catch(e){console.warn(e)}const q=new URLSearchParams(location.search),r=q.get('result');if(r&&restoreActive()){history.replaceState({},'',location.pathname);r==='done'?go('complete'):r==='notdone'?go('notDone'):(renderActivity(),go('activity'))}});
newTry();newPointless();renderLook();